.\" Manpage for ympd.
.\" Contact andy@ympd.org to correct errors or typos.
.TH man 1 "19 Oct 2014" "1.2.3" "ympd man page"
.SH NAME
ympd \- Standalone MPD Web GUI written in C, utilizing Websockets and Bootstrap/JS
.SH SYNOPSIS
ympd [OPTION]...
.SH DESCRIPTION
ympd is a lightweight MPD (Music Player Daemon) web client that runs without a dedicated webserver or interpreters like PHP, NodeJS or Ruby. It's tuned for minimal resource usage and requires only very litte dependencies.

ympd is based in part on the work of the mongoose http server (https://github.com/cesanta/mongoose)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-host HOST\fR
connect to mpd at host, defaults to localhost
.TP
\fB\-p\fR, \fB\-\-port PORT\fR
connect to mpd at port, defaults to 6600
.TP
\fB\-w\fR, \fB\-\-webport PORT\fR
specifies the port for the webserver to listen to, defaults to 8080
.TP
\fB\-u\fR, \fB\-\-user username\fR
drop privileges to the provided username after socket binding
.TP
\fB\-V\fR, \fB\-\-version\fR
print version and exit
.TP
\fB\-\-help\fR
print all valid options and exits
.SH BUGS
No known bugs.
.SH AUTHOR
Andrew Karpow (andy@ndyk.de)

http://www.ympd.org
